spring:
  application:
    name: zuul

server:
  port: 8092

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8088/eureka/

feign:
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000

service:
  provider:
    name:
      - eureka-client
      - service-provider

zuul:
  routes:
    # service-a is just a name of route rule.
    service-a:

      path: /eureka-client/**

      # when the route matches the path, it will get forward to the microservice as below
      serviceId: ${service.provider.name[0]}
