spring:
  application:
    name: feign-consumer
  sleuth:
    sampler:
      probability: 0.1

server:
  port: 8091

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8088/eureka/

service:
  provider:
    name:
      - eureka-client

feign:
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000